---
title: "Prepare data"
format: html
---

```{r}
library(tidyverse)
```

## Data 1

```{r}
dir.create("./data/sim/data-1/", recursive = TRUE, showWarnings = FALSE)

set.seed(9899)

for (i in 1:50) {
  this_participant_q <- tibble(
    date = Sys.Date() + i,
    Q1 = sample(c("yes", "no"), 1),
    Q2 = sample(c("frequently", "sometimes", "rarely"), 1),
    Q3a = sample(1:5, 1),
    Q3b = sample(1:5, 1),
    Q3c = sample(1:5, 1),
    Q3d = sample(1:5, 1),
    Q3e = sample(1:5, 1)
  )
  
  this_participant_form <- tibble(
    date = Sys.Date() + i,
    type = rep("form", 4),
    question = c(sample(c("gender:NB", "gender:F", "gender:M", "gender:O"), 1), "age", "group", "biling_score"),
    value = c(
      NA,
      paste0(sample(18:42, 1), sample(c("", "yo", " yo", " year old"), 1)),
      sample(c("monolingual", "bilingual"), 1),
      round(rbeta(1, 5, 1) * 100)
    )
  )
  
  this_participant <- bind_rows(this_participant_q, this_participant_form)
  
  this_file <- paste0("data/sim/data-1/pid-", i, ".csv")
  write_csv(this_participant, this_file)
  these_lines <- read_lines(this_file)
  to_skip <- "# created with AwesomeExperimenter 0.1, (c) Polly Darton"
  write_lines(c(to_skip, these_lines), file = this_file)
}

data_1_exp <- tibble()
ps <- rbeta(50, 5, 1)

for (i in 1:50) {
  this_p <- ps[i]
  this_participant <- tibble(
    id = i,
    type = c(rep("practice", 10), rep("test", 20)),
    condition = c(rep(NA, 10), sample(c("easy", "difficult"), 20, replace = TRUE)),
    accuracy = rbinom(30, 1, this_p),
    rt = exp(rnorm(30, 6.5, 1))
  )
  data_1_exp <- bind_rows(data_1_exp, this_participant)
}

write_csv(data_1_exp, "data/sim/data-1-exp.csv")
```

## Data 2

```{r}
#| label: everywhere-loc

everywhere_loc <- read_csv("https://osf.io/download/vaujp/?view_only=edba6a2255044ce6af6a519b85c9e65f") %>%
  select(-(Simple:Pass))

dir.create("./data/sluckin2022/")
write_csv(everywhere_loc, file = "./data/sluckin2022/everywhere-loc.csv")
```

